Change component group name for AEMaaS artifacts
adobe/aem-core-wcm-components pull request #1216
Opened 2020-10-16 16:28 UTC by bpauli

- added componentGroup properties for cloud and non-cloud profile
- enabled JCR root filtering in the filevault-maven-plugin for properties substitution

2020-10-19 12:21 UTC, jckautzmann approved these changes

2020-10-19 14:09 UTC, msagolj requested changes

2020-10-19 14:14 UTC, msagolj commented
Probably something for a separate issue but I just noted that the `progess bar` is the only component without an icon:

![image](https://user-images.githubusercontent.com/37147400/96462370-c863b680-1225-11eb-8e61-116d2251715f.png)

2020-10-20 09:32 UTC, bpauli commented on content/src/content/jcr_root/apps/core/wcm/components/form/text/v1/text/.content.xml
> +    componentGroup="${componentGroup}"/>
Good catch! fixed in the last commit.

2020-10-20 14:07 UTC, msagolj approved these changes

2020-10-21 08:09 UTC, merged