Cif 1512
adobe/aem-core-wcm-components pull request #1336
Opened 2021-01-08 10:39 UTC by cjelger

As discussed with @vladbailescu , I am moving some localization methods to a new "OSGi-exported" utils class, so that they can be reused by other components like the commerce experience fragment component added by https://github.com/adobe/aem-core-cif-components/pull/458

I didn't add any test because this code is already covered by the existing tests in `ExperienceFragmentImplTest`

2021-01-19 09:50 UTC, vladbailescu requested changes

2021-01-19 12:38 UTC, cjelger commented on bundles/core/src/main/java/com/adobe/cq/wcm/core/components/util/LocalizationUtils.java
> +    public static String getLocalizationRoot(@NotNull String path, @NotNull ResourceResolver resolver,
Thx for the feedback: I replaced the path argument with the resource.

2021-01-25 20:33 UTC, jckautzmann commented
In an other PR, we created the `com.adobe.cq.wcm.core.components.internal.LocalizationUtils` class as part of an internal package:
https://github.com/adobe/aem-core-wcm-components/blob/development/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/LocalizationUtils.java

Should we also expose its methods as part of the public API and add them to `com.adobe.cq.wcm.core.components.util.LocalizationUtils`?

cc: @cjelger @vladbailescu @bpauli @ky940819

2021-01-26 06:10 UTC, bpauli commented
In [1] @ky940819 mentioned that there are several (pre-existing) issues with the `com.adobe.cq.wcm.core.components.internal.LocalizationUtils` logic and therefore he decided to make this class private. Maybe we have to do some rework before we can it to a public API.

[1] https://github.com/adobe/aem-core-wcm-components/pull/1253

2021-01-26 08:26 UTC, jckautzmann approved these changes

2021-01-26 10:14 UTC, merged