[Page][AMP] Allow customers that use AMP Page (v1) to keep using clie…
adobe/aem-core-wcm-components pull request #2114
Opened 2022-03-28 21:15 UTC by jckautzmann

…ntlibs that do not load well in async mode

- introduce a policy config to enable/disable async loading of custom JS clientlibs

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #2113 
| Patch: Bug Fix?          |
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

2022-03-29 12:11 UTC, bpauli requested changes
It would probably make sense to introduce two checkboxes to control the async behaviour for the `clientlibsJsHead` and `clientlibs` individual. WDYT?

2022-03-31 07:52 UTC, jckautzmann commented on bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v3/PageImplTest.java
> +        assertFalse(async);
@bpauli I added more tests in https://github.com/adobe/aem-core-wcm-components/pull/2114/commits/530320295327bcf5e3551e91239cdd2df229679f and https://github.com/adobe/aem-core-wcm-components/pull/2114/commits/42711b16a719251a418373be51fd21ccce3965a2

2022-03-31 07:57 UTC, jckautzmann commented
@bpauli 
>It would probably make sense to introduce two checkboxes to control the async behaviour for the clientlibsJsHead and clientlibs individual. WDYT?

As a first iteration we decided to have only one checkbox to enable/disable async loading for all the clientlibs defined for the page. We will re-discuss this behaviour with @gabrielwalt when he is back.

2022-03-31 09:15 UTC, bpauli approved these changes

2022-03-31 15:25 UTC, merged